### ISSUE TITLE
连不上腾讯手游模拟器

### ISSUE THREAD

**Issue by lcj0012** [LSC527/jgm_auto_load#7]
按键精灵里代码已经复制上了，进行到链接模拟器这步，电脑上腾讯手游模拟器已开，但按键精灵扫描不到设备，无法连接

**Comment by LSC527** [comment]
实在连不上就手动在模拟器里装个按键精灵手机版（有可能已经有了），然后打开，再手动连接模拟器，这时模拟器里按键精灵界面里就会有一个弹窗问是否连接

**Comment by lcj0012** [comment]
腾讯手游模拟器里搜索不到按键精灵

**Comment by lcj0012** [comment]
我知道啦，3和4之间还有一步调试，先调试就会自动安按键精灵了
